#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== WeeklyOps Prompt Setup ==="
echo ""

# --- Step 1: Pick your name ---
echo "Who are you?"
echo ""
NAMES=("Chris" "Mary-Margaret" "Fathima" "Isaac" "Avery" "MD" "Tyler" "David")
for i in "${!NAMES[@]}"; do
    echo "  $((i+1))) ${NAMES[$i]}"
done
echo ""
read -rp "Enter number (1-${#NAMES[@]}): " choice

if [[ "$choice" -lt 1 || "$choice" -gt "${#NAMES[@]}" ]]; then
    echo "Invalid choice. Run make setup again."
    exit 1
fi

USER_NAME="${NAMES[$((choice-1))]}"
echo "  → $USER_NAME"
echo ""

# --- Step 2: API key ---
if [ -f "$PROJECT_DIR/.env" ] && grep -q "WEEKLYOPS_API_KEY=." "$PROJECT_DIR/.env" 2>/dev/null; then
    echo "API key already configured in .env"
    read -rp "Replace it? (y/N): " replace
    if [[ "$replace" != "y" && "$replace" != "Y" ]]; then
        echo "  → Keeping existing key"
    else
        read -rp "Paste your WeeklyOps API key: " api_key
        echo "WEEKLYOPS_API_KEY=$api_key" > "$PROJECT_DIR/.env"
        echo "  → Key saved to .env"
    fi
else
    read -rp "Paste your WeeklyOps API key: " api_key
    echo "WEEKLYOPS_API_KEY=$api_key" > "$PROJECT_DIR/.env"
    echo "  → Key saved to .env"
fi
echo ""

# --- Step 3: Write config.yaml ---
cat > "$PROJECT_DIR/config.yaml" <<YAML
# WeeklyOps Prompt — User Configuration
# Generated by make setup on $(date +%Y-%m-%d)

user:
  name: "$USER_NAME"
YAML
echo "  → config.yaml updated (user: $USER_NAME)"
echo ""

# --- Step 4: Generate .mcp.json ---
# Read the API key
source "$PROJECT_DIR/.env"

if [ -z "${WEEKLYOPS_API_KEY:-}" ]; then
    echo "WARNING: WEEKLYOPS_API_KEY is empty. MCP connection will not work."
    echo "Set it in .env and run make setup again."
else
    cat > "$PROJECT_DIR/.mcp.json" <<JSON
{
  "mcpServers": {
    "weeklyops": {
      "command": "npx",
      "args": [
        "mcp-remote",
        "https://weeklyops.membies.com/mcp",
        "--header",
        "Authorization: Bearer $WEEKLYOPS_API_KEY"
      ]
    }
  }
}
JSON
    echo "  → .mcp.json generated (MCP connection configured)"
fi
echo ""

# --- Step 5: Run doctor ---
echo "Running health checks..."
echo ""
bash "$SCRIPT_DIR/doctor.sh"

echo ""
echo "=== Setup Complete ==="
echo "Open Claude Code in this directory and start talking."
echo ""
echo "Try these commands:"
echo "  /email-scan        — Generate an email analysis prompt"
echo "  /email-ingest      — Process email scan output"
echo "  /weekly-update     — Weekly self-review"
